// <auto-generated />
using System;
using DevXuongMoc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevXuongMoc.Migrations
{
    [DbContext(typeof(DevXuongMocContext))]
    [Migration("20241220192844_CreatePaymentMethodTable")]
    partial class CreatePaymentMethodTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevXuongMoc.Models.AdminLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ACTION_CODE");

                    b.Property<string>("ActionName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ACTION_NAME");

                    b.Property<int?>("ActionType")
                        .HasColumnType("int")
                        .HasColumnName("ACTION_TYPE");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("int")
                        .HasColumnName("ADMIN_USER_ID");

                    b.Property<string>("AppCode")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("APP_CODE");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTENT");

                    b.Property<string>("Description")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("END_TIME");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ERROR_CODE");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<int?>("LogLevel")
                        .HasColumnType("int")
                        .HasColumnName("LOG_LEVEL");

                    b.Property<string>("MenuCode")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("MENU_CODE");

                    b.Property<string>("MenuName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MENU_NAME");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("int")
                        .HasColumnName("OBJECT_ID");

                    b.Property<string>("SessionId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SESSION_ID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("START_TIME");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("THREAD_ID");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("USER_LOGIN");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_NAME");

                    b.Property<int?>("WebpagesActionId")
                        .HasColumnType("int")
                        .HasColumnName("WEBPAGES_ACTION_ID");

                    b.HasKey("LogId")
                        .HasName("PK__ADMIN_LO__4364C88279FADB84");

                    b.ToTable("ADMIN_LOG", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ACCOUNT");

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AVATAR");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("IdPhongBan")
                        .HasColumnType("int")
                        .HasColumnName("ID_PHONG_BAN");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ADMIN");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETE");

                    b.Property<int?>("MaNhanSu")
                        .HasColumnType("int")
                        .HasColumnName("MA_NHAN_SU");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAY_CAP_NHAT");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAY_TAO");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NGUOI_CAP_NHAT");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NGUOI_TAO");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Salt")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("SALT")
                        .IsFixedLength();

                    b.Property<string>("SessionToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SESSION_TOKEN");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TRANG_THAI");

                    b.HasKey("Id")
                        .HasName("PK__ADMIN_US__3214EC2739901ACE");

                    b.ToTable("ADMIN_USER", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IMAGE");

                    b.Property<bool>("Isdelete")
                        .HasColumnType("bit")
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTES");

                    b.Property<int>("Orders")
                        .HasColumnType("int")
                        .HasColumnName("ORDERS");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("STATUS");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SUB_TITLE");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TITLE");

                    b.Property<string>("Type")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TYPE");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<string>("Urls")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("URLS");

                    b.HasKey("Id")
                        .HasName("PK__BANNER__3214EC274D7E8BD5");

                    b.ToTable("BANNER", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ICON");

                    b.Property<bool?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("MateTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MATE_TITLE");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_DESCRIPTION");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("Notes")
                        .HasColumnType("ntext")
                        .HasColumnName("NOTES");

                    b.Property<int?>("Orders")
                        .HasColumnType("int")
                        .HasColumnName("ORDERS");

                    b.Property<int?>("Parentid")
                        .HasColumnType("int")
                        .HasColumnName("PARENTID");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SLUG");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__PRODUCT___A88186B13985BFD1");

                    b.ToTable("CATEGORY", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<string>("Content")
                        .HasColumnType("ntext")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<bool?>("Isdelete")
                        .HasColumnType("bit")
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PHONE");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id");

                    b.ToTable("CONTACT", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AVATAR");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ISACTIVE");

                    b.Property<bool?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("PHONE");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id")
                        .HasName("PK__CUSTOMER__3214EC27C6498DFD");

                    b.HasIndex(new[] { "Username" }, "UQ__CUSTOMER__B15BE12E1CAE99DA")
                        .IsUnique();

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Extension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ICON");

                    b.Property<bool?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_DESCRIPTION");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_TITLE");

                    b.Property<string>("Notes")
                        .HasColumnType("ntext")
                        .HasColumnName("NOTES");

                    b.Property<int?>("Orders")
                        .HasColumnType("int")
                        .HasColumnName("ORDERS");

                    b.Property<int?>("Parentid")
                        .HasColumnType("int")
                        .HasColumnName("PARENTID");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SLUG");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__PRODUCT___EXTENSION");

                    b.ToTable("EXTENSION", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.InforCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Facebook")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FACEBOOK");

                    b.Property<string>("Instagram")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("INSTAGRAM");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("LOGO");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_DESCRIPTION");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_TITLE");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PHONE");

                    b.Property<DateOnly?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("Youtube")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("YOUTUBE");

                    b.HasKey("Id");

                    b.ToTable("INFOR_COMPANY", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Introduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<byte?>("Home")
                        .HasColumnType("tinyint")
                        .HasColumnName("HOME");

                    b.Property<string>("Image")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("NO_IMAGE_AVAILABLE.jpg")
                        .HasColumnName("IMAGE");

                    b.Property<bool>("Isdelete")
                        .HasColumnType("bit")
                        .HasColumnName("ISDELETE");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("META_DESCRIPTION");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_TITLE");

                    b.Property<int?>("Orders")
                        .HasColumnType("int")
                        .HasColumnName("ORDERS");

                    b.Property<int?>("Parentid")
                        .HasColumnType("int")
                        .HasColumnName("PARENTID");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SLUG");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TITLE");

                    b.Property<byte?>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("TYPE");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__INTRODUC__3214EC2715DFAD94");

                    b.ToTable("INTRODUCTIONS", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ICON");

                    b.Property<bool?>("Isdelete")
                        .HasColumnType("bit")
                        .HasColumnName("ISDELETE");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_DESCRIPTION");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_TITLE");

                    b.Property<string>("Notes")
                        .HasColumnType("ntext")
                        .HasColumnName("NOTES");

                    b.Property<int?>("Orders")
                        .HasColumnType("int")
                        .HasColumnName("ORDERS");

                    b.Property<int?>("Parentid")
                        .HasColumnType("int")
                        .HasColumnName("PARENTID");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SLUG");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK__MATERIAL___EXTENSION");

                    b.ToTable("MATERIAL", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODE");

                    b.Property<string>("Content")
                        .HasColumnType("ntext")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Image")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("NO_IMAGE_AVAILABLE.jpg")
                        .HasColumnName("IMAGE");

                    b.Property<bool?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ISDELETE");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("LIKES");

                    b.Property<string>("MainKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MAIN_KEYWORD");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_DESCRIPTION");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_TITLE");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SLUG");

                    b.Property<double?>("Star")
                        .HasColumnType("float")
                        .HasColumnName("STAR");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Views")
                        .HasColumnType("int")
                        .HasColumnName("VIEWS");

                    b.HasKey("Id")
                        .HasName("PK__NEWS__3214EC27E639B94D");

                    b.ToTable("NEWS", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("Idcustomer")
                        .HasColumnType("int")
                        .HasColumnName("IDCUSTOMER");

                    b.Property<string>("Idorders")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IDORDERS");

                    b.Property<int?>("Idpayment")
                        .HasColumnType("int")
                        .HasColumnName("IDPAYMENT");

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ISACTIVE");

                    b.Property<bool?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("NameReceiver")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME_RECEIVER");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTES");

                    b.Property<DateTime?>("OrdersDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ORDERS_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("PHONE");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TOTAL_MONEY");

                    b.HasKey("Id")
                        .HasName("PK__ORDERS__3214EC27F782221C");

                    b.HasIndex("Idcustomer");

                    b.HasIndex(new[] { "Idorders" }, "UQ__ORDERS__99356D841119ADD1")
                        .IsUnique();

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.OrdersDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Idord")
                        .HasColumnType("int")
                        .HasColumnName("IDORD");

                    b.Property<int>("Idproduct")
                        .HasColumnType("int")
                        .HasColumnName("IDPRODUCT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("QTY");

                    b.Property<int?>("ReturnQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("RETURN_QTY");

                    b.Property<decimal?>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasColumnName("TOTAL")
                        .HasComputedColumnSql("([PRICE]*[QTY])", true);

                    b.HasKey("Id")
                        .HasName("PK__ORDERS_D__3214EC27F9A636F6");

                    b.HasIndex("Idord");

                    b.HasIndex("Idproduct");

                    b.ToTable("ORDERS_DETAILS", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Logo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("NO_IMAGE_AVAILABLE.jpg")
                        .HasColumnName("LOGO");

                    b.Property<byte?>("Orders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ORDERS");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("URL");

                    b.HasKey("Id")
                        .HasName("PK__PARTNER__3214EC27A833D94A");

                    b.ToTable("PARTNER", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("DevXuongMoc.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<int?>("Cid")
                        .HasColumnType("int")
                        .HasColumnName("CID");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODE");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<byte?>("Home")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("HOME");

                    b.Property<byte?>("Hot")
                        .HasColumnType("tinyint")
                        .HasColumnName("HOT");

                    b.Property<string>("Image")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("NO_IMAGE_AVAILABLE.jpg")
                        .HasColumnName("IMAGE");

                    b.Property<bool?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ISDELETE");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("LIKES");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_DESCRIPTION");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_TITLE");

                    b.Property<decimal?>("PriceNew")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("PRICE_NEW");

                    b.Property<decimal?>("PriceOld")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("PRICE_OLD");

                    b.Property<string>("Size")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SIZE");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SLUG");

                    b.Property<double?>("Star")
                        .HasColumnType("float")
                        .HasColumnName("STAR");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Views")
                        .HasColumnType("int")
                        .HasColumnName("VIEWS");

                    b.HasKey("Id")
                        .HasName("PK__PRODUCT__3214EC27E639B94D");

                    b.ToTable("PRODUCT", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.ProductExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("ntext")
                        .HasColumnName("CONTENT");

                    b.Property<int?>("Eid")
                        .HasColumnType("int")
                        .HasColumnName("EID");

                    b.Property<int?>("Pid")
                        .HasColumnType("int")
                        .HasColumnName("PID");

                    b.HasKey("Id")
                        .HasName("PK_PRODUCTEXTENSIONS");

                    b.ToTable("PRODUCT_EXTENSIONS", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("IMAGE");

                    b.Property<int?>("Pid")
                        .HasColumnType("int")
                        .HasColumnName("PID");

                    b.HasKey("Id")
                        .HasName("PK_PRODUCTIMAGES");

                    b.ToTable("PRODUCT_IMAGES", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.ProductMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Mid")
                        .HasColumnType("int")
                        .HasColumnName("MID");

                    b.Property<int?>("Pid")
                        .HasColumnType("int")
                        .HasColumnName("PID");

                    b.HasKey("Id")
                        .HasName("PK_PRODUCTMATERIALS");

                    b.ToTable("PRODUCT_MATERIALS", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCreated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_CREATED");

                    b.Property<string>("AdminUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADMIN_UPDATED");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Image")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("NO_IMAGE_AVAILABLE.jpg")
                        .HasColumnName("IMAGE");

                    b.Property<bool>("Isdelete")
                        .HasColumnType("bit")
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTES");

                    b.Property<int>("Orders")
                        .HasColumnType("int")
                        .HasColumnName("ORDERS");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("STATUS");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SUB_TITLE");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Urls")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("URLS");

                    b.HasKey("Id")
                        .HasName("PK__SLIDES__3214EC27231D6CCE");

                    b.ToTable("SLIDES", (string)null);
                });

            modelBuilder.Entity("DevXuongMoc.Models.Order", b =>
                {
                    b.HasOne("DevXuongMoc.Models.Customer", "IdcustomerNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Idcustomer")
                        .IsRequired()
                        .HasConstraintName("FK__ORDERS__IDCUSTOM__2180FB33");

                    b.Navigation("IdcustomerNavigation");
                });

            modelBuilder.Entity("DevXuongMoc.Models.OrdersDetail", b =>
                {
                    b.HasOne("DevXuongMoc.Models.Order", "IdordNavigation")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("Idord")
                        .IsRequired()
                        .HasConstraintName("FK__ORDERS_DE__IDORD__25518C17");

                    b.HasOne("DevXuongMoc.Models.Product", "IdproductNavigation")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("Idproduct")
                        .IsRequired()
                        .HasConstraintName("FK__ORDERS_DE__IDPRO__2645B050");

                    b.Navigation("IdordNavigation");

                    b.Navigation("IdproductNavigation");
                });

            modelBuilder.Entity("DevXuongMoc.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DevXuongMoc.Models.Order", b =>
                {
                    b.Navigation("OrdersDetails");
                });

            modelBuilder.Entity("DevXuongMoc.Models.Product", b =>
                {
                    b.Navigation("OrdersDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
